input_config: 
    var: [zmta, zmua]
    folder: /mnt/2data/solarisheppa/
    simulation: [refC2]
    model: [CESM1-WACCM]
    ens: [r3i1p1]
analysis:
    s_year: 1960
    e_year: 2090
    type: [annually,monthly]
    reg_config: SH_regressors
    rho: 2
output_config:
    folder: /mnt/2data/solarisheppa/outputs/
SH_regressors:
    QBO50: 
        filename: /mnt/2data/solarisheppa/regressors/bernd/internal_proxies_for_refc2_WACCM_r3.nc
        norm_type: std_scaling
        norm_const: null
    QBO30:
        filename: /mnt/2data/solarisheppa/regressors/bernd/internal_proxies_for_refc2_WACCM_r3.nc
        norm_type: std_scaling
        norm_const: null
    ENSO:
        filename: /mnt/2data/solarisheppa/regressors/bernd/internal_proxies_for_refc2_WACCM_r3.nc
        norm_type: std_scaling
        norm_const: null
    f107:
        filename: /mnt/2data/solarisheppa/regressors/bernd/solar_proxies_for_refc2_solaris_heppa.nc
        norm_type: null
        norm_const: null
    epp_for_t_and_u:
        filename: /mnt/2data/solarisheppa/regressors/bernd/solar_proxies_for_refc2_solaris_heppa.nc
        norm_type: null
        norm_const: null
    spe_for_t_and_u:
        filename: /mnt/2data/solarisheppa/regressors/bernd/solar_proxies_for_refc2_solaris_heppa.nc
        norm_type: null
        norm_const: null
    CO2EQ:
        filename: /mnt/2data/solarisheppa/regressors/bernd/anthropogenic_proxies_for_refc2.nc
        norm_type: null
        norm_const: null
    EESC:
        filename: /mnt/2data/solarisheppa/regressors/bernd/anthropogenic_proxies_for_refc2.nc
        norm_type: null
        norm_const: null



    